apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-php-apache"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      initContainers:
        - name: init-php-apache
          image: busybox
          volumeMounts:
          - name: php-apache-persistent-storage
            mountPath: /var/www/html
          command: ['sh', '-c', "wget -qO- https://wordpress.org/latest.tar.gz | tar xvz -C /tmp/ && mv /tmp/wordpress/* /var/www/html/"]
      containers:
        - name: php-apache
          image: {{ .Values.phpApache.image }}
          ports:
          - containerPort: {{ .Values.phpApache.port }}
          volumeMounts:
          - name: php-apache-persistent-storage
            mountPath: /var/www/html
      volumes:
      - name: php-apache-persistent-storage
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-php-apache-pv-claim"