apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-persistants-volume-apache"
spec:
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/data/{{ .Release.Name }}-apache"